//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_ActiveOdo
    {
        public long OdoID { get; set; }
        public string ObjectID { get; set; }
        public string ObjectRegNum { get; set; }
        public Nullable<System.DateTime> GPSTime { get; set; }
        public byte GPSFlag { get; set; }
        public Nullable<System.DateTime> LastDataTime { get; set; }
        public bool IsActive { get; set; }
        public byte CurTransType { get; set; }
        public int MileAge { get; set; }
        public short MaxSpeed { get; set; }
        public Nullable<System.DateTime> MaxSpeedTime { get; set; }
        public string MaxSpeedLat { get; set; }
        public string MaxSpeedLon { get; set; }
        public int Distance { get; set; }
        public decimal Fuel { get; set; }
        public decimal UsageFuel { get; set; }
        public int usagemileage { get; set; }
        public decimal dailyfuel { get; set; }
        public int EstFuel { get; set; }
        public int ObjectMileage { get; set; }
        public int OdoCounter { get; set; }
    }
}
