//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_AllUserFee
    {
        public string ObjectID { get; set; }
        public string ObjectRegNum { get; set; }
        public string GSMVoiceNum { get; set; }
        public string ObjectBrand { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactCardID { get; set; }
        public string ContactAddr { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> Servicecharge { get; set; }
        public Nullable<int> FeeCount { get; set; }
    }
}
