//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_AlarmDisposal
    {
        public int DisposalID { get; set; }
        public int AlarmID { get; set; }
        public Nullable<System.DateTime> Disposaltime { get; set; }
        public string Disposaltype { get; set; }
        public string DisposalDes { get; set; }
        public Nullable<decimal> Lon { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public Nullable<short> Direct { get; set; }
        public string Cur_Location { get; set; }
        public string StatusDes { get; set; }
        public string Remark { get; set; }
        public string Operator { get; set; }
    }
}
