//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Arrive
    {
        public int StationID { get; set; }
        public string RoadName { get; set; }
        public string ObjectID { get; set; }
        public string VName { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public string Arrive { get; set; }
        public string Station { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public string Destination { get; set; }
    }
}
