//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_BetweenStation
    {
        public long ID { get; set; }
        public Nullable<int> RectID { get; set; }
        public string ObjectID { get; set; }
        public Nullable<byte> RoadPercent { get; set; }
        public Nullable<int> RoadID { get; set; }
        public Nullable<byte> ObjectStatus { get; set; }
        public Nullable<System.DateTime> CurrentTime { get; set; }
    }
}
