//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Category
    {
        public int Ctg_ID { get; set; }
        public string Ctg_Name { get; set; }
        public string Ctg_Sign { get; set; }
        public string Ctg_Spec { get; set; }
        public string Ctg_Unit { get; set; }
        public Nullable<decimal> Ctg_Inprice { get; set; }
        public Nullable<decimal> Ctg_Tradeprice { get; set; }
        public Nullable<decimal> Ctg_Retailprice { get; set; }
        public string Ctg_Image1 { get; set; }
        public string Ctg_Image2 { get; set; }
        public bool IsActive { get; set; }
        public string Remark { get; set; }
    }
}
