//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_CTIOutCall
    {
        public int OutCallID { get; set; }
        public Nullable<int> TrunksID { get; set; }
        public string CallOutNum { get; set; }
        public Nullable<byte> CallType { get; set; }
        public Nullable<System.DateTime> CalloutTime { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> offTime { get; set; }
        public string CallTitle { get; set; }
    
        public virtual A_CTITrunk A_CTITrunk { get; set; }
    }
}
