//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_CTIRecord
    {
        public int RecordID { get; set; }
        public Nullable<int> TrunksID { get; set; }
        public Nullable<System.DateTime> Starttime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string FileName { get; set; }
        public string Remark { get; set; }
    
        public virtual A_CTITrunk A_CTITrunk { get; set; }
    }
}
