//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_CustomerInput
    {
        public string REGISTERNO { get; set; }
        public string OBJECTID { get; set; }
        public string SUECONTENT { get; set; }
        public Nullable<System.DateTime> SUEDATE { get; set; }
        public string SUENAMETYPE { get; set; }
        public string SUEMAN { get; set; }
        public string SUETEL { get; set; }
        public string SUEADDRESS { get; set; }
        public string SUEEMAIL { get; set; }
        public string SUEREMARK { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> REGISTERTIME { get; set; }
        public string SUERESULT { get; set; }
    }
}
