//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Discontent
    {
        public int ID { get; set; }
        public string Discontent_ID { get; set; }
        public string RepairID { get; set; }
        public string InstallID { get; set; }
        public byte Discontent_Type { get; set; }
        public string Discontent { get; set; }
        public string Discontent_Contactor { get; set; }
        public string Discontent_Tel { get; set; }
        public string Discontent_Addr { get; set; }
        public string Discontent_Email { get; set; }
        public Nullable<byte> Discontent_Flag { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
