//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_DriverInfo
    {
        public int DriverID { get; set; }
        public string DriverWorkID { get; set; }
        public string Driver_Name { get; set; }
        public Nullable<byte> Driver_Status { get; set; }
        public string DriverPWD { get; set; }
        public string DriveCard_NO { get; set; }
        public Nullable<byte> DriveCard_Type { get; set; }
        public string DriveCard_BakNO { get; set; }
        public string ObjectID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> DriverGroupID { get; set; }
        public string Contacter { get; set; }
        public string Driver_CardID { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string OfficePhone { get; set; }
        public string BPCall { get; set; }
        public string Sex { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ContactMan1 { get; set; }
        public string ContactPhone1 { get; set; }
        public string MobilePhone1 { get; set; }
        public string ContactMan2 { get; set; }
        public string ContactPhone2 { get; set; }
        public string MobilePhone2 { get; set; }
    }
}
