//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_EmployeeInfo
    {
        public int EmployeeID { get; set; }
        public string EmployeeWorkID { get; set; }
        public int DepartID { get; set; }
        public string EmployeeName { get; set; }
        public string Employeenative { get; set; }
        public string Employeeresident { get; set; }
        public Nullable<bool> Employeemarried { get; set; }
        public Nullable<byte> Employeedegree { get; set; }
        public string Employeegrad { get; set; }
        public string Employeemajor { get; set; }
        public string Employeeminor { get; set; }
        public string CardID { get; set; }
        public Nullable<byte> EmployeeType { get; set; }
        public string EmployeeTitle { get; set; }
        public string Contacter { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> ComeInTime { get; set; }
        public Nullable<System.DateTime> EmployedTime { get; set; }
        public Nullable<System.DateTime> FireTime { get; set; }
        public string Remark { get; set; }
        public bool IssActive { get; set; }
        public string Createuser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
