//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Event
    {
        public int EventID { get; set; }
        public string VID { get; set; }
        public Nullable<int> EventType { get; set; }
        public Nullable<int> EventStatus { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public Nullable<System.DateTime> GPSTime { get; set; }
        public Nullable<double> Mileage { get; set; }
        public Nullable<double> Lon { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> Direct { get; set; }
        public Nullable<int> GPSFlag { get; set; }
        public Nullable<double> Fuel { get; set; }
        public string StatusDes { get; set; }
    }
}
