//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_FeeIncome
    {
        public string ObjectID { get; set; }
        public Nullable<System.DateTime> IncomeTime { get; set; }
        public Nullable<decimal> IncomeFee { get; set; }
        public string IncomeType { get; set; }
        public string WriterUser { get; set; }
    }
}
