//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_FeePayout
    {
        public string ObjectID { get; set; }
        public System.DateTime PayoutTime { get; set; }
        public Nullable<decimal> PayoutFee { get; set; }
        public string PayoutType { get; set; }
        public string WriterUser { get; set; }
    }
}
