//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_GeoReport
    {
        public decimal RecID { get; set; }
        public string ObjectID { get; set; }
        public Nullable<System.DateTime> GPSTime { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public Nullable<int> Odo { get; set; }
        public Nullable<int> Course { get; set; }
        public Nullable<decimal> Lon { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public string StatusDes { get; set; }
        public Nullable<decimal> GeoID { get; set; }
        public Nullable<decimal> Type { get; set; }
        public Nullable<System.DateTime> RcvTime { get; set; }
        public Nullable<decimal> Fuel { get; set; }
        public bool IsEmailSend { get; set; }
        public bool IsTeleSend { get; set; }
        public Nullable<System.DateTime> TeleSendTime { get; set; }
        public Nullable<System.DateTime> EmailSendTime { get; set; }
    }
}
