//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_HourReport
    {
        public int hour { get; set; }
        public Nullable<int> C00_Load { get; set; }
        public Nullable<int> C00_Empty { get; set; }
        public Nullable<int> C10_Load { get; set; }
        public Nullable<int> C10_Empty { get; set; }
        public Nullable<int> C20_Load { get; set; }
        public Nullable<int> C20_Empty { get; set; }
        public Nullable<int> C30_Load { get; set; }
        public Nullable<int> C30_Empty { get; set; }
        public Nullable<int> C40_Load { get; set; }
        public Nullable<int> C40_Empty { get; set; }
        public Nullable<int> C50_Load { get; set; }
        public Nullable<int> C50_Empty { get; set; }
    }
}
