//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_ICCard
    {
        public string ICCardID { get; set; }
        public string ObjectID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<byte> ICCardType { get; set; }
        public string ICCardPWD { get; set; }
        public string SerialNO { get; set; }
        public Nullable<bool> IsWriteMDT { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
    }
}
