//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_ICLog
    {
        public int logID { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string EmployeeWorkID { get; set; }
        public string ICCardID { get; set; }
        public string ObjectID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<byte> LogStatus { get; set; }
        public string remark { get; set; }
    }
}
