//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_InstallInfo
    {
        public string InstallBillID { get; set; }
        public string Sal_ID { get; set; }
        public string ObjectID { get; set; }
        public int EmployeeID { get; set; }
        public string InstallAddr { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<byte> GuardDevice { get; set; }
        public Nullable<byte> Checkitem { get; set; }
        public Nullable<byte> BeforeisOK { get; set; }
        public string BeforeMemo { get; set; }
        public Nullable<byte> AfterisOK { get; set; }
        public string AfterMemo { get; set; }
        public Nullable<byte> Terminal { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Createuser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
