//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_MapStreetInfo
    {
        public int ID { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public decimal Lon { get; set; }
        public decimal Lat { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
