//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_MDTInfo
    {
        public int MDTID { get; set; }
        public string TerminalID { get; set; }
        public string MDTCompany { get; set; }
        public string MDTType { get; set; }
        public string ProtocolVer { get; set; }
        public string AlarmNum { get; set; }
        public string MonitorNum { get; set; }
        public string CenterNum_1 { get; set; }
        public string CenterNum_2 { get; set; }
        public string CenterNum_3 { get; set; }
        public string TranslateTel { get; set; }
        public string ISP { get; set; }
        public Nullable<bool> NeedCloseBP { get; set; }
        public Nullable<bool> NeedCloseLCD { get; set; }
        public Nullable<bool> PermitCall { get; set; }
        public Nullable<bool> PermitPickup { get; set; }
        public string DriverPWD_1 { get; set; }
        public string DriverPWD_2 { get; set; }
        public string DriverPWD_3 { get; set; }
        public string DriverPWD_4 { get; set; }
        public string MDTSetupParm { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string DeviceType { get; set; }
    }
}
