//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_OneUserFee
    {
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<System.DateTime> RcvTime { get; set; }
        public string TransType { get; set; }
        public string Content { get; set; }
        public string Describe { get; set; }
        public string CommandType { get; set; }
        public string SendSource { get; set; }
    }
}
