//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Point
    {
        public int PointID { get; set; }
        public Nullable<int> RoadID { get; set; }
        public string PointName { get; set; }
        public Nullable<decimal> Lon { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<int> Direct { get; set; }
        public Nullable<int> Mile { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> Station { get; set; }
        public string FullName { get; set; }
        public Nullable<decimal> SegAvgSpeed { get; set; }
    }
}
