//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_RegObject
    {
        public int RegID { get; set; }
        public string TagID { get; set; }
        public string CardNo { get; set; }
        public string Name { get; set; }
        public string PhoneNum { get; set; }
        public string Address { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
    }
}
