//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Reminder
    {
        public int IDD { get; set; }
        public string ObjectID { get; set; }
        public string ObjectRegNum { get; set; }
        public string TypeAlert { get; set; }
        public Nullable<System.DateTime> TglReminder { get; set; }
        public Nullable<System.DateTime> TglUpdate { get; set; }
        public Nullable<System.DateTime> TglProses { get; set; }
        public Nullable<bool> Flag { get; set; }
    }
}
