//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_RoadReport
    {
        public int ID { get; set; }
        public string ObjectID { get; set; }
        public Nullable<System.DateTime> InOutTime { get; set; }
        public string VName { get; set; }
        public Nullable<System.DateTime> GPSTime { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> Odo { get; set; }
        public Nullable<int> Direct { get; set; }
        public Nullable<decimal> Lon { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<int> RoadID { get; set; }
        public string MDTStatus { get; set; }
    }
}
