//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Road_Vehicle
    {
        public string VehicleID { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleSIM { get; set; }
        public string curRoadID { get; set; }
        public string WriteRoadIDs { get; set; }
        public System.DateTime WcurTime { get; set; }
        public System.DateTime WTime { get; set; }
    }
}
