//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Road
    {
        public int RoadID { get; set; }
        public string RoadName { get; set; }
        public Nullable<int> Offset { get; set; }
        public Nullable<int> Spacing { get; set; }
        public Nullable<int> Radius { get; set; }
        public Nullable<short> Platform { get; set; }
        public Nullable<int> Speed { get; set; }
    }
}
