//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_RoadData
    {
        public decimal ID { get; set; }
        public string RoadID { get; set; }
        public int PointID { get; set; }
        public double Lon { get; set; }
        public double Lat { get; set; }
        public string Status { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Number { get; set; }
        public string Name { get; set; }
        public Nullable<int> AreaRange { get; set; }
        public Nullable<System.DateTime> AlarmTimeB { get; set; }
        public Nullable<System.DateTime> AlarmTimeE { get; set; }
        public Nullable<int> Speed { get; set; }
        public string TYPE { get; set; }
    }
}
