//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Road_StationReport
    {
        public decimal ID { get; set; }
        public string VehicleNo { get; set; }
        public string curRoadID { get; set; }
        public string curRoadName { get; set; }
        public Nullable<int> S_StationID { get; set; }
        public string S_StationName { get; set; }
        public string S_STime { get; set; }
        public string S_RSTime { get; set; }
        public Nullable<int> E_StationID { get; set; }
        public string E_StationName { get; set; }
        public string E_ETime { get; set; }
        public string E_RETime { get; set; }
        public string Status { get; set; }
    }
}
