//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Road_SpeedReport
    {
        public decimal ID { get; set; }
        public string RoadID { get; set; }
        public string VehicleNo { get; set; }
        public string TimeRange { get; set; }
        public string TimeDesc { get; set; }
        public string AverageSpeed { get; set; }
        public string MaxSpeed { get; set; }
        public string TotalMileAge { get; set; }
        public string StopTime { get; set; }
        public string ValidTime { get; set; }
        public string OverSpeedLen { get; set; }
        public string OverSpeedTime { get; set; }
    }
}
