//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_RoadInfo
    {
        public string RoadID { get; set; }
        public string RoadName { get; set; }
        public Nullable<System.DateTime> WTime { get; set; }
        public Nullable<int> PointNum { get; set; }
        public Nullable<System.DateTime> AlarmTimeB { get; set; }
        public Nullable<System.DateTime> AlarmTimeE { get; set; }
        public Nullable<int> Speed { get; set; }
        public string RoadDes { get; set; }
        public Nullable<double> RoadLength { get; set; }
        public Nullable<int> RoadTypeNum { get; set; }
        public Nullable<int> WPointNum { get; set; }
        public Nullable<int> BranchNum { get; set; }
    }
}
