//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Sale
    {
        public int ID { get; set; }
        public string Sal_ID { get; set; }
        public Nullable<int> Ctg_ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> Sal_Qty { get; set; }
        public Nullable<decimal> Sal_Price { get; set; }
        public Nullable<decimal> Sal_Discount { get; set; }
        public Nullable<decimal> Sal_SumFee { get; set; }
        public Nullable<byte> Sal_Status { get; set; }
        public Nullable<byte> Sal_Type { get; set; }
        public string Sal_Receiver { get; set; }
        public string Sal_Rcvaddr { get; set; }
        public string Sal_Rcvtel { get; set; }
        public string Sal_ApplyMemo { get; set; }
        public string Sal_AuditMemo { get; set; }
        public Nullable<byte> Sal_ServiceStatus { get; set; }
        public string Sal_ServiceFee { get; set; }
        public string Applier { get; set; }
        public Nullable<System.DateTime> Applydate { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<byte> Sal_SalFlag { get; set; }
        public Nullable<byte> Sal_PayFlag { get; set; }
        public Nullable<byte> Sal_WhsOutStatus { get; set; }
        public Nullable<byte> Sal_WhsOutType { get; set; }
        public Nullable<byte> Sal_CollectFlag { get; set; }
    }
}
