//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_StationInfo
    {
        public string RoadID { get; set; }
        public int StationID { get; set; }
        public string StationName { get; set; }
        public string StationProperty { get; set; }
        public string StationType { get; set; }
        public Nullable<double> StationX { get; set; }
        public Nullable<double> StationY { get; set; }
        public Nullable<double> StationDX { get; set; }
        public Nullable<double> StationDY { get; set; }
    }
}
