//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_SueInfo
    {
        public int SueID { get; set; }
        public string ObjectID { get; set; }
        public string SueContent { get; set; }
        public Nullable<System.DateTime> SueDate { get; set; }
        public string SueMan { get; set; }
        public string SueTel { get; set; }
        public Nullable<System.DateTime> DealDate { get; set; }
        public string DealContent { get; set; }
        public string DealMan { get; set; }
        public string Response { get; set; }
        public string Operator { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
