//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_VehicleTeamInfo
    {
        public int VehicleTeamID { get; set; }
        public string VehicleTeamName { get; set; }
        public int CompanyID { get; set; }
        public string LeaderName { get; set; }
        public string Telphone { get; set; }
        public string ContactAddr { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
    }
}
