//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Warehouse
    {
        public int whs_ID { get; set; }
        public string Whs_name { get; set; }
        public string Whs_addr { get; set; }
        public string Whs_contact { get; set; }
        public string Whs_tel { get; set; }
        public bool IsActive { get; set; }
        public string remark { get; set; }
    }
}
