//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_WebGISRxTxNew
    {
        public int ID { get; set; }
        public string ObjectID { get; set; }
        public string SendCMD { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string ResponseContent { get; set; }
        public Nullable<short> SendFlag { get; set; }
        public string UserID { get; set; }
    }
}
