//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_WeekReport
    {
        public int myHour { get; set; }
        public Nullable<double> Monday { get; set; }
        public Nullable<double> Tuesday { get; set; }
        public Nullable<double> Wednesday { get; set; }
        public Nullable<double> Thursday { get; set; }
        public Nullable<double> Friday { get; set; }
        public Nullable<double> Saturday { get; set; }
        public Nullable<double> Sunday { get; set; }
    }
}
