//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_WhsOut
    {
        public int ID { get; set; }
        public string WhsOut_ID { get; set; }
        public int StkCtg_ID { get; set; }
        public string Sal_ID { get; set; }
        public string WhsOut_SumQty { get; set; }
        public string WhsOut_InfactQty { get; set; }
        public string WhsOut_Man { get; set; }
        public string WhsOut_Addr { get; set; }
        public string WhsOut_Tel { get; set; }
        public string WhsOut_User { get; set; }
        public Nullable<System.DateTime> WhsOut_Date { get; set; }
        public string WhsOut_InvQty { get; set; }
        public string WhsOut_Collector { get; set; }
        public Nullable<System.DateTime> WhsOut_CollDate { get; set; }
    }
}
