//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_WhsStock
    {
        public int Stkctg_ID { get; set; }
        public int Whs_ID { get; set; }
        public int Ctg_ID { get; set; }
        public string Whs_StkQty { get; set; }
        public Nullable<byte> Whs_Status { get; set; }
    }
}
