//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_ADInfo
    {
        public int ID { get; set; }
        public string ADContent { get; set; }
        public Nullable<byte> Display { get; set; }
        public Nullable<byte> Speed { get; set; }
        public Nullable<byte> StopTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Creator { get; set; }
    }
}
