//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AM_APIKeyGoogleLog
    {
        public decimal IDLogApi { get; set; }
        public Nullable<decimal> Lon { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public string Location { get; set; }
        public string APIKey { get; set; }
        public Nullable<System.DateTime> TimeUpdate { get; set; }
        public Nullable<long> IDRoad { get; set; }
        public System.Data.Entity.Spatial.DbGeography geom { get; set; }
    }
}
