//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AM_APIKeyGoogle
    {
        public int IDAPI { get; set; }
        public string APIKey { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> TotalUsage { get; set; }
    }
}
