//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class C30324680_20180807
    {
        public decimal TracksID { get; set; }
        public string ObjectID { get; set; }
        public string ObjectRegNum { get; set; }
        public string GSMVoiceNum { get; set; }
        public string GSMDataNum { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<double> Lon { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public Nullable<short> Direct { get; set; }
        public System.DateTime GPSTime { get; set; }
        public System.DateTime LastDataTime { get; set; }
        public Nullable<byte> GPSFlag { get; set; }
        public string Cur_Location { get; set; }
        public string MDTStatus { get; set; }
        public string OperateStatus { get; set; }
        public Nullable<byte> TransType { get; set; }
        public string StatusDes { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> StateInt { get; set; }
        public Nullable<int> MileAge { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Exhaust { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<decimal> smoke { get; set; }
        public string TagID { get; set; }
        public Nullable<decimal> Temp2 { get; set; }
        public string StatusDes2 { get; set; }
    }
}
