//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoordinatesMatrix
    {
        public int address_id { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public string location { get; set; }
        public Nullable<decimal> longitude_ceil { get; set; }
        public Nullable<decimal> latitude_ceil { get; set; }
        public Nullable<decimal> longitude_floor { get; set; }
        public Nullable<decimal> latitude_floor { get; set; }
    }
}
