//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_DictDetail
    {
        public int DictID { get; set; }
        public int ItemID { get; set; }
        public string ItemValue { get; set; }
        public string Remark { get; set; }
    
        public virtual D_DictMaster D_DictMaster { get; set; }
    }
}
