//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_DriveCard_Type
    {
        public byte DriveCard_Type { get; set; }
        public string DriveCard_TypeDet { get; set; }
        public string remark { get; set; }
    }
}
