//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_MapList
    {
        public byte ID { get; set; }
        public string MapName { get; set; }
        public string MAPXTREME { get; set; }
        public string HQWEBMAP { get; set; }
    }
}
