//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_ObjectIcon
    {
        public byte ObjectType { get; set; }
        public byte Statustype { get; set; }
        public byte[] East { get; set; }
        public byte[] SouthEast { get; set; }
        public byte[] South { get; set; }
        public byte[] southwest { get; set; }
        public byte[] West { get; set; }
        public byte[] northwest { get; set; }
        public byte[] North { get; set; }
        public byte[] NorthEast { get; set; }
        public string remark { get; set; }
    }
}
