//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dyan_AlertEvent
    {
        public string ObjectID { get; set; }
        public string ObjectRegNum { get; set; }
        public string AlertType { get; set; }
        public Nullable<System.DateTime> GPSTime { get; set; }
        public string StatusDes { get; set; }
        public string Lon { get; set; }
        public string Lat { get; set; }
        public short Speed { get; set; }
        public Nullable<System.DateTime> ProcessTime { get; set; }
        public bool IsEmailSend { get; set; }
        public bool IsEmailSendDaily { get; set; }
        public Nullable<System.DateTime> LastDataTime { get; set; }
        public int CustomerId { get; set; }
        public int GISGroupId { get; set; }
        public int Duration { get; set; }
    }
}
