//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dyan_CustomerAlertReminder
    {
        public int CustomerID { get; set; }
        public bool IsAlertEmail { get; set; }
        public bool IsReminderEmail { get; set; }
        public string EmailAddress { get; set; }
        public short IdleLimit { get; set; }
        public short ParkingLimit { get; set; }
        public short SpeedLimit { get; set; }
        public short BbmLimit { get; set; }
        public bool IsSOS { get; set; }
        public bool IsGPSCut { get; set; }
        public bool IsBatteryCut { get; set; }
        public bool IsSensor1 { get; set; }
        public bool IsAlertSms { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsInactiveEmail { get; set; }
        public byte DaysReminder { get; set; }
        public short Overspeed { get; set; }
        public bool IsGeofence { get; set; }
        public bool IsSmsTracking { get; set; }
        public string CustomerName { get; set; }
        public short IdleInterval { get; set; }
        public bool IsSensor2 { get; set; }
        public bool IsParking { get; set; }
        public bool IsIdle { get; set; }
    }
}
