//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dyan_ParkingCounter
    {
        public string ObjectID { get; set; }
        public Nullable<System.DateTime> GPSTime { get; set; }
        public string LastStatus { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public short Speed { get; set; }
        public short EventStatus { get; set; }
    }
}
