//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_InfoCustomMaster
    {
        public int CustomID { get; set; }
        public string SimNO { get; set; }
        public Nullable<System.DateTime> CustomTime { get; set; }
        public string ReserveParam { get; set; }
    }
}
