//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_InfoContent
    {
        public int InfoID { get; set; }
        public Nullable<int> InfoTypeID { get; set; }
        public string ReserveParam { get; set; }
        public string InfoContent { get; set; }
        public Nullable<System.DateTime> RecTime { get; set; }
    }
}
