//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_InfoRxTmp
    {
        public int RxID { get; set; }
        public string RxContent { get; set; }
        public string ReqSimNO { get; set; }
        public Nullable<System.DateTime> ReqTime { get; set; }
        public Nullable<byte> CommChannel { get; set; }
        public Nullable<decimal> Lon { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<short> Direct { get; set; }
        public string MDTStatus { get; set; }
    }
}
