//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MAPDBEntities : DbContext
    {
        public MAPDBEntities()
            : base("name=MAPDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barangay> Barangays { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CoordinatesMatrix> CoordinatesMatrices { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Matrix_1> Matrix_1 { get; set; }
        public virtual DbSet<Matrix_10> Matrix_10 { get; set; }
        public virtual DbSet<Road> Roads { get; set; }
        public virtual DbSet<Road1> Roads1 { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<AM_APIKeyGoogle> AM_APIKeyGoogle { get; set; }
        public virtual DbSet<AM_APIKeyGoogleLog> AM_APIKeyGoogleLog { get; set; }
    
        public virtual ObjectResult<string> sp_GetLocation(Nullable<double> lon, Nullable<double> lat)
        {
            var lonParameter = lon.HasValue ?
                new ObjectParameter("Lon", lon) :
                new ObjectParameter("Lon", typeof(double));
    
            var latParameter = lat.HasValue ?
                new ObjectParameter("Lat", lat) :
                new ObjectParameter("Lat", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetLocation", lonParameter, latParameter);
        }
    
        public virtual int sp_InsertBarangay(string name, string lINESTRING, Nullable<double> lon, Nullable<double> lat, Nullable<int> matrix_10, string districtName)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var lINESTRINGParameter = lINESTRING != null ?
                new ObjectParameter("lINESTRING", lINESTRING) :
                new ObjectParameter("lINESTRING", typeof(string));
    
            var lonParameter = lon.HasValue ?
                new ObjectParameter("Lon", lon) :
                new ObjectParameter("Lon", typeof(double));
    
            var latParameter = lat.HasValue ?
                new ObjectParameter("Lat", lat) :
                new ObjectParameter("Lat", typeof(double));
    
            var matrix_10Parameter = matrix_10.HasValue ?
                new ObjectParameter("Matrix_10", matrix_10) :
                new ObjectParameter("Matrix_10", typeof(int));
    
            var districtNameParameter = districtName != null ?
                new ObjectParameter("DistrictName", districtName) :
                new ObjectParameter("DistrictName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertBarangay", nameParameter, lINESTRINGParameter, lonParameter, latParameter, matrix_10Parameter, districtNameParameter);
        }
    
        public virtual int sp_InsertMatrix1(Nullable<int> iD, string lINESTRING, Nullable<int> matrix_10)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var lINESTRINGParameter = lINESTRING != null ?
                new ObjectParameter("lINESTRING", lINESTRING) :
                new ObjectParameter("lINESTRING", typeof(string));
    
            var matrix_10Parameter = matrix_10.HasValue ?
                new ObjectParameter("Matrix_10", matrix_10) :
                new ObjectParameter("Matrix_10", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertMatrix1", iDParameter, lINESTRINGParameter, matrix_10Parameter);
        }
    
        public virtual int sp_InsertMatrix10(Nullable<int> iD, string lINESTRING)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var lINESTRINGParameter = lINESTRING != null ?
                new ObjectParameter("lINESTRING", lINESTRING) :
                new ObjectParameter("lINESTRING", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertMatrix10", iDParameter, lINESTRINGParameter);
        }
    
        public virtual int sp_InsertRoad(string name, string lINESTRING, Nullable<double> lon, Nullable<double> lat, Nullable<int> matrix_10, string barangay, Nullable<int> matrix_1)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var lINESTRINGParameter = lINESTRING != null ?
                new ObjectParameter("lINESTRING", lINESTRING) :
                new ObjectParameter("lINESTRING", typeof(string));
    
            var lonParameter = lon.HasValue ?
                new ObjectParameter("Lon", lon) :
                new ObjectParameter("Lon", typeof(double));
    
            var latParameter = lat.HasValue ?
                new ObjectParameter("Lat", lat) :
                new ObjectParameter("Lat", typeof(double));
    
            var matrix_10Parameter = matrix_10.HasValue ?
                new ObjectParameter("Matrix_10", matrix_10) :
                new ObjectParameter("Matrix_10", typeof(int));
    
            var barangayParameter = barangay != null ?
                new ObjectParameter("Barangay", barangay) :
                new ObjectParameter("Barangay", typeof(string));
    
            var matrix_1Parameter = matrix_1.HasValue ?
                new ObjectParameter("Matrix_1", matrix_1) :
                new ObjectParameter("Matrix_1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertRoad", nameParameter, lINESTRINGParameter, lonParameter, latParameter, matrix_10Parameter, barangayParameter, matrix_1Parameter);
        }
    
        public virtual ObjectResult<string> sp_ReverseGeocodeCM(Nullable<double> latitude, Nullable<double> longitude)
        {
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("latitude", latitude) :
                new ObjectParameter("latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("longitude", longitude) :
                new ObjectParameter("longitude", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_ReverseGeocodeCM", latitudeParameter, longitudeParameter);
        }
    }
}
