//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matrix_10
    {
        public int ID { get; set; }
        public System.Data.Entity.Spatial.DbGeography geom { get; set; }
        public string sgeom { get; set; }
    }
}
