//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGPS_Track_Cannonball
    {
        public int ID { get; set; }
        public string AssetID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public Nullable<System.DateTime> DataTime { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<int> Odometer { get; set; }
    }
}
