//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGPS_TelegramConfig
    {
        public int config_id { get; set; }
        public string chat_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
