//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGPS_UserLogs
    {
        public int log_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> log_time { get; set; }
        public Nullable<bool> log_type { get; set; }
        public string app { get; set; }
        public string ip { get; set; }
    }
}
