//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGPS_UserReport
    {
        public int Id { get; set; }
        public Nullable<int> ReportId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Enabled { get; set; }
    }
}
