//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGPS_Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PGPS_Schedule()
        {
            this.PGPS_AssetSchedule = new HashSet<PGPS_AssetSchedule>();
        }
    
        public int sched_id { get; set; }
        public string name { get; set; }
        public Nullable<System.TimeSpan> from_am { get; set; }
        public Nullable<System.TimeSpan> to_am { get; set; }
        public Nullable<System.TimeSpan> from_pm { get; set; }
        public Nullable<System.TimeSpan> to_pm { get; set; }
        public Nullable<int> week_value { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> alert_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PGPS_AssetSchedule> PGPS_AssetSchedule { get; set; }
    }
}
