//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGPS_Leaderboard
    {
        public decimal LeaderboardID { get; set; }
        public string AssetID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<double> CP1 { get; set; }
        public Nullable<System.DateTime> CPE1 { get; set; }
        public Nullable<System.DateTime> CPS1 { get; set; }
        public Nullable<double> CP2 { get; set; }
        public Nullable<System.DateTime> CPE2 { get; set; }
        public Nullable<System.DateTime> CPS2 { get; set; }
        public Nullable<double> CP3 { get; set; }
        public Nullable<System.DateTime> CPE3 { get; set; }
        public Nullable<System.DateTime> CPS3 { get; set; }
        public Nullable<double> CP4 { get; set; }
        public Nullable<System.DateTime> CPE4 { get; set; }
        public Nullable<System.DateTime> CPS4 { get; set; }
        public Nullable<double> CP5 { get; set; }
        public Nullable<System.DateTime> CPE5 { get; set; }
        public Nullable<System.DateTime> CPS5 { get; set; }
        public Nullable<double> CP6 { get; set; }
        public Nullable<System.DateTime> CPE6 { get; set; }
        public Nullable<System.DateTime> CPS6 { get; set; }
        public Nullable<decimal> AverageSpeed { get; set; }
        public Nullable<decimal> MaxSpeed { get; set; }
        public Nullable<int> TotalDuration { get; set; }
        public Nullable<int> Ranking { get; set; }
    }
}
