//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGPS_SensorType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PGPS_SensorType()
        {
            this.PGPS_SensorSetting = new HashSet<PGPS_SensorSetting>();
        }
    
        public int sensor_type_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string metric_units { get; set; }
        public string english_units { get; set; }
        public Nullable<double> max_value { get; set; }
        public Nullable<double> min_value { get; set; }
        public Nullable<int> sensor_value { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PGPS_SensorSetting> PGPS_SensorSetting { get; set; }
    }
}
