//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGPS_ObjectDelivery
    {
        public int object_delivery_id { get; set; }
        public string delivery_number { get; set; }
        public string object_id { get; set; }
        public string object_name { get; set; }
        public Nullable<System.DateTime> creation_datetime { get; set; }
        public Nullable<System.DateTime> start_datetime { get; set; }
        public Nullable<System.DateTime> end_datetime { get; set; }
        public string start_location { get; set; }
        public string end_location { get; set; }
        public Nullable<double> start_longitude { get; set; }
        public Nullable<double> start_latitude { get; set; }
        public Nullable<double> end_longitude { get; set; }
        public Nullable<double> end_latitude { get; set; }
        public Nullable<int> user_id { get; set; }
        public string remarks { get; set; }
        public string description { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<bool> cancelled { get; set; }
        public Nullable<System.DateTime> last_report_datetime { get; set; }
        public Nullable<System.DateTime> last_query_datetime { get; set; }
        public string delivery_status { get; set; }
        public bool process_auto { get; set; }
        public string order_number { get; set; }
        public Nullable<System.DateTime> zonestart_datetime { get; set; }
        public Nullable<System.DateTime> zoneend_datetime { get; set; }
        public int odo_start { get; set; }
        public int odo_end { get; set; }
        public Nullable<double> zonestart_longitude { get; set; }
        public Nullable<double> zonestart_latitude { get; set; }
        public int zonestart_odo { get; set; }
        public Nullable<double> zoneend_longitude { get; set; }
        public Nullable<double> zoneend_latitude { get; set; }
        public int zoneend_odo { get; set; }
        public int DriverID { get; set; }
        public Nullable<System.DateTime> receive_datetime { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public int distance_google { get; set; }
    }
}
