//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGPS_TelegramEvent
    {
        public int TeleEventID { get; set; }
        public string ObjectID { get; set; }
        public string Name { get; set; }
        public string StatusDes { get; set; }
        public Nullable<System.DateTime> GPSTime { get; set; }
        public Nullable<System.DateTime> EventGPSTime { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<System.DateTime> TeleSendTime { get; set; }
        public Nullable<bool> IsSend { get; set; }
    }
}
