//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Road
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public System.Data.Entity.Spatial.DbGeography geom { get; set; }
        public Nullable<decimal> Lon { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<int> Matrix_10 { get; set; }
        public string Barangay { get; set; }
        public Nullable<int> Matrix_1 { get; set; }
        public string Nama { get; set; }
        public Nullable<int> Flaggoogle { get; set; }
        public Nullable<int> Flag { get; set; }
    }
}
