//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_RoleFun
    {
        public int RoleFunID { get; set; }
        public int RoleID { get; set; }
        public int FunID { get; set; }
    
        public virtual S_SysFun S_SysFun { get; set; }
        public virtual S_SysRole S_SysRole { get; set; }
    }
}
