//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_SysFun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public S_SysFun()
        {
            this.S_RoleFun = new HashSet<S_RoleFun>();
        }
    
        public int FunID { get; set; }
        public int AppID { get; set; }
        public Nullable<int> P_FunID { get; set; }
        public string FunName { get; set; }
        public string FunURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_RoleFun> S_RoleFun { get; set; }
        public virtual S_SysApp S_SysApp { get; set; }
    }
}
