//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_SysUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public S_SysUser()
        {
            this.S_UserRole = new HashSet<S_UserRole>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string Password { get; set; }
        public string Default_map { get; set; }
        public Nullable<System.DateTime> Available_StartTime { get; set; }
        public Nullable<System.DateTime> Available_EndTime { get; set; }
        public string remark { get; set; }
        public bool IsActive { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string GroupCode { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string api_key { get; set; }
        public Nullable<bool> api_status { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> LastEmailUpdate { get; set; }
        public string EncryptedPassword { get; set; }
        public Nullable<int> parent_account { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_UserRole> S_UserRole { get; set; }
    }
}
