//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CekVersion
    {
        public string ObjectID { get; set; }
        public string ObjectRegNum { get; set; }
        public string Customer_Name { get; set; }
        public string MDTCompany { get; set; }
        public string ProtocolVer { get; set; }
        public string MDTType { get; set; }
    }
}
