//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PGPS_CurrentObjectTracks
    {
        public string ObjectID { get; set; }
        public string ObjectName { get; set; }
        public string SimNumber { get; set; }
        public int GroupCode { get; set; }
        public Nullable<byte> ObjectType { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<byte> FuelType { get; set; }
        public Nullable<decimal> FuelRatio { get; set; }
        public Nullable<System.DateTime> GPSTime { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public Nullable<short> Direction { get; set; }
        public string Status { get; set; }
        public string MDTStatus { get; set; }
        public Nullable<int> Odometer { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> LastDataTime { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerContact { get; set; }
        public string CustomerEmail { get; set; }
    }
}
