//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SueInfo
    {
        public string RegisterNo { get; set; }
        public string SUEMAN { get; set; }
        public Nullable<System.DateTime> SueDate { get; set; }
        public string ObjectID { get; set; }
        public string SueContent { get; set; }
        public string SUENAMETYPE { get; set; }
        public string SueTel { get; set; }
        public string SueAddress { get; set; }
        public string SUERESULT { get; set; }
        public Nullable<System.DateTime> AcceptTime { get; set; }
        public string REASON { get; set; }
        public Nullable<System.DateTime> DealDate { get; set; }
        public string DealContent { get; set; }
        public string DealMan { get; set; }
    }
}
