//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TripPerCustomer
    {
        public int TripID { get; set; }
        public string VID { get; set; }
        public string VName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> TravelDuration { get; set; }
        public Nullable<int> StopDuration { get; set; }
        public Nullable<int> AvgSpeed { get; set; }
        public Nullable<int> MaxSpeed { get; set; }
        public Nullable<double> Lon { get; set; }
        public Nullable<double> Lat { get; set; }
    }
}
