//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_Module
    {
        public int ModuleID { get; set; }
        public string ModuleName { get; set; }
        public string ModuleText { get; set; }
        public string ModulePic { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> SysTypeID { get; set; }
        public string Remark { get; set; }
    
        public virtual W_SysType W_SysType { get; set; }
    }
}
