//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public int ZoneId { get; set; }
        public double AreaInMeters { get; set; }
        public int ZoneTypeId { get; set; }
    
        public virtual Geofence Geofence { get; set; }
        public virtual ZoneType ZoneType { get; set; }
    }
}
