//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_ObjectInfo
    {
        public A_ObjectInfo()
        {
            this.PGPS_ObjectDelivery = new HashSet<PGPS_ObjectDelivery>();
            this.PGPS_ObjectDriver = new HashSet<PGPS_ObjectDriver>();
            this.PGPS_SensorSetting = new HashSet<PGPS_SensorSetting>();
        }
    
        public string ObjectID { get; set; }
        public string ObjectRegNum { get; set; }
        public string GSMDataNum { get; set; }
        public string GSMVoiceNum { get; set; }
        public int GISGroupID { get; set; }
        public byte CommChannel { get; set; }
        public Nullable<byte> ObjectStatus { get; set; }
        public Nullable<byte> ObjectType { get; set; }
        public Nullable<System.DateTime> ObjectRegDate { get; set; }
        public string ObjectColor { get; set; }
        public Nullable<byte> capacityType { get; set; }
        public Nullable<int> GroupNo { get; set; }
        public string MonitorCorp { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactBP { get; set; }
        public string ContactCardID { get; set; }
        public string ContactAddr { get; set; }
        public string AlarmRoute { get; set; }
        public Nullable<int> MDTID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ObjectEngine { get; set; }
        public string VehicleshelfNum { get; set; }
        public Nullable<System.DateTime> OutFactory { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public string VehicleBodyNum { get; set; }
        public Nullable<System.DateTime> LastCheckDate { get; set; }
        public string GuardDevice { get; set; }
        public string DeviceFunction { get; set; }
        public Nullable<bool> IsDeviceOK { get; set; }
        public string InsureTime { get; set; }
        public string InsureComp { get; set; }
        public string InsureID { get; set; }
        public Nullable<byte> InsureType { get; set; }
        public string InsureMoney { get; set; }
        public string InsureSeller { get; set; }
        public string InsureSeller_Tel { get; set; }
        public string BusinessID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> vehicleTeamID { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ObjectModel { get; set; }
        public Nullable<int> SubcenterID { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<bool> IfLoginAlarm { get; set; }
        public Nullable<System.DateTime> AlarmStartTime { get; set; }
        public Nullable<System.DateTime> AlarmEndTime { get; set; }
        public string ObjectBrand { get; set; }
        public Nullable<byte> FuelType { get; set; }
        public Nullable<decimal> FuelRatio { get; set; }
        public Nullable<System.DateTime> Registration { get; set; }
        public Nullable<System.DateTime> Insurance { get; set; }
        public Nullable<System.DateTime> Permit { get; set; }
        public Nullable<System.DateTime> License { get; set; }
        public Nullable<System.DateTime> LastService { get; set; }
        public Nullable<int> ServiceOdo { get; set; }
        public string Accessory { get; set; }
        public Nullable<bool> SendEmail { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<int> Schedule { get; set; }
        public int Interval { get; set; }
        public string ServiceProvider { get; set; }
    
        public virtual A_ActiveTracks A_ActiveTracks { get; set; }
        public virtual ICollection<PGPS_ObjectDelivery> PGPS_ObjectDelivery { get; set; }
        public virtual ICollection<PGPS_ObjectDriver> PGPS_ObjectDriver { get; set; }
        public virtual ICollection<PGPS_SensorSetting> PGPS_SensorSetting { get; set; }
    }
}
