//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_ObjectType
    {
        public byte ObjectType { get; set; }
        public string ObjectTypeDet { get; set; }
        public byte[] East { get; set; }
        public byte[] SouthEast { get; set; }
        public byte[] South { get; set; }
        public byte[] southwest { get; set; }
        public byte[] West { get; set; }
        public byte[] northwest { get; set; }
        public byte[] North { get; set; }
        public byte[] NorthEast { get; set; }
        public byte[] A_East { get; set; }
        public byte[] A_SouthEast { get; set; }
        public byte[] A_South { get; set; }
        public byte[] A_southwest { get; set; }
        public byte[] A_West { get; set; }
        public byte[] A_northwest { get; set; }
        public byte[] A_North { get; set; }
        public byte[] A_NorthEast { get; set; }
        public byte[] V_East { get; set; }
        public byte[] V_SouthEast { get; set; }
        public byte[] V_South { get; set; }
        public byte[] V_southwest { get; set; }
        public byte[] V_West { get; set; }
        public byte[] V_northwest { get; set; }
        public byte[] V_North { get; set; }
        public byte[] V_NorthEast { get; set; }
        public string remark { get; set; }
        public Nullable<int> ObjectOrder { get; set; }
    }
}
