//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGPS_Tag
    {
        public PGPS_Tag()
        {
            this.PGPS_Driver = new HashSet<PGPS_Driver>();
        }
    
        public int TagId { get; set; }
        public string Type { get; set; }
        public string Code { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual A_CustomerInfo A_CustomerInfo { get; set; }
        public virtual ICollection<PGPS_Driver> PGPS_Driver { get; set; }
    }
}
