//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGPS_ReportTypes
    {
        public PGPS_ReportTypes()
        {
            this.PGPS_CustomerReports = new HashSet<PGPS_CustomerReports>();
            this.PGPS_EmailReports = new HashSet<PGPS_EmailReports>();
        }
    
        public int ReportTypesID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PGPS_CustomerReports> PGPS_CustomerReports { get; set; }
        public virtual ICollection<PGPS_EmailReports> PGPS_EmailReports { get; set; }
    }
}
