//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGPS_UserSettings
    {
        public int UserSettingsID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> LastEmailUpdate { get; set; }
        public Nullable<int> SoundNotification { get; set; }
        public Nullable<System.DateTime> TRA_LastLogin { get; set; }
        public Nullable<decimal> TRA_LoginExpiry { get; set; }
    
        public virtual S_SysUser S_SysUser { get; set; }
    }
}
