//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_SysRole
    {
        public S_SysRole()
        {
            this.S_UserRole = new HashSet<S_UserRole>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public bool Deleteflag { get; set; }
        public Nullable<int> RoleValue { get; set; }
    
        public virtual ICollection<S_UserRole> S_UserRole { get; set; }
    }
}
