//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Philgps_WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebServers
    {
        public WebServers()
        {
            this.WebServerConfiguration = new HashSet<WebServerConfiguration>();
        }
    
        public int web_server_id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public string code { get; set; }
        public string config_name { get; set; }
        public string default_coordinates { get; set; }
        public string downloads_url { get; set; }
        public string images_url { get; set; }
    
        public virtual ICollection<WebServerConfiguration> WebServerConfiguration { get; set; }
    }
}
